= Teragrep Authorization Module for Apache Kafka

== Features

Same Teragrep authorization format as used in link:https://github.com/teragrep/pth_05/[pth_05]

Teragrep Kafka Authorizer authorizes Kafka authenticated users to access the topics according to the `authorize.json` rules.

== Configuration

Groups which are authorized to access topics reside in `/opt/teragrep/kaf_04/etc/authorize.json` file.

Cluster user must be provided in `/opt/teragrep/kaf_04/etc/cluster.json` file.

Writer user must be provided in `/opt/teragrep/kaf_04/etc/writer.json` file.

== Documentation

See the official documentation on https://docs.teragrep.com[docs.teragrep.com].

== How to use

[source,shell script]
----
CLASSPATH=/opt/teragrep/kaf_04/share/kaf_04.jar kafka-server-start.sh
----

== Contributing

You can involve yourself with our project by https://github.com/teragrep/kaf_04/issues/new/choose[opening an issue] or submitting a pull request.

Contribution requirements:

. *All changes must be accompanied by a new or changed test.* If you think testing is not required in your pull request, include a sufficient explanation as why you think so.
. Security checks must pass
. Pull requests must align with the principles and http://www.extremeprogramming.org/values.html[values] of extreme programming.
. Pull requests must follow the principles of Object Thinking and Elegant Objects (EO).

Read more in our https://github.com/teragrep/teragrep/blob/main/contributing.adoc[Contributing Guideline].

=== Contributor License Agreement

Contributors must sign https://github.com/teragrep/teragrep/blob/main/cla.adoc[Teragrep Contributor License Agreement] before a pull request is accepted to organization's repositories.

You need to submit the CLA only once. After submitting the CLA you can contribute to all Teragrep's repositories.
