name: CI

on: [ push ]

jobs:
  upload:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Local Maven Repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 8.0.292+10
          distribution: 'adopt'

      - name: Run CI
        run: mvn --batch-mode clean verify

      - name: Prepare RPM GPG signing
        run: |
          sudo apt-get install expect pinentry-tty;
          printf "RPM_SIGNING_KEYNAME=%q\n" "$(echo "${{ secrets.RPM_SIGNING_PUBLIC_KEY }}" | gpg --show-keys --with-colons | awk -F':' '/uid/{print $10}')" >> $GITHUB_ENV;
          echo "${{ secrets.RPM_SIGNING_PRIVATE_KEY }}" | gpg --batch --import;
          echo "%_gpg_sign_cmd_extra_args --pinentry-mode loopback --passphrase \"%{getenv:RPM_SIGNING_PASSPHRASE}\"" >> "${HOME}/.rpmmacros";

      - name: Download latest kaf_06 rpm
        run: gh release download --repo teragrep/kaf_06 --dir src/test/integration/rpm/ --pattern "*.rpm"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Build RPM for integration tests
        run: cd rpm/ && mvn --batch-mode -Drevision=${{ github.run_id }} -Dsha1= -Dchangelist= -f rpm.pom.xml package && find target/ -type f -name "*.rpm" -exec mv {} ../src/test/integration/rpm/ \;
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RPM_SIGNING_KEYNAME: ${{ env.RPM_SIGNING_KEYNAME }}
          RPM_SIGNING_PASSPHRASE: ${{ secrets.RPM_SIGNING_PASSPHRASE }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: Build integration test image
        run: cd src/test/integration/ && docker buildx build --output type=docker --tag integration-test:latest  .

      - name: Run integration tests
        run: docker run --interactive integration-test:latest
